server {
  listen 80;

  # Serve the static files from this directory
  root /usr/share/nginx/html;

  # For any request that doesn't match a file, serve index.html
  location / {
    try_files $uri /index.html;
  }
}