# Generated by Django 4.2.11 on 2026-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('censo', 'Censo'), ('registro', 'Registro')], max_length=50)),
                ('drive_link', models.URLField(max_length=500)),
                ('mapa', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('etnia', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('camara', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
