# Generated by Django 4.2.11 on 2026-06-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='fecha_creacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='prompt_usado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='resolucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='usuario_creador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
