# Generated by Django 4.2.11 on 2026-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_videometadata_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videometadata',
            old_name='fecha_creacion',
            new_name='aceptado',
        ),
        migrations.RenameField(
            model_name='videometadata',
            old_name='usuario_creador',
            new_name='estilizado',
        ),
        migrations.RenameField(
            model_name='videometadata',
            old_name='resolucion',
            new_name='id_video_equipo',
        ),
        migrations.RenameField(
            model_name='videometadata',
            old_name='thumbnail_url',
            new_name='imagen_link',
        ),
        migrations.RenameField(
            model_name='videometadata',
            old_name='prompt_usado',
            new_name='prompt_final',
        ),
        migrations.AddField(
            model_name='videometadata',
            name='mateo_miguel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='prompt_imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='prompt_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='video_original_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
