# Generated by Django 4.2.11 on 2026-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_rename_fecha_creacion_videometadata_aceptado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadata',
            name='drive_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videometadata',
            name='video_id',
            field=models.CharField(max_length=100),
        ),
    ]
