# Generated by Django 4.2.11 on 2026-06-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_alter_videometadata_drive_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='imagen_arreglo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='prompt_imagen_arreglo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='prompt_video_arreglo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='video_arreglo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
