# Generated by Django 4.2.11 on 2026-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_videometadata_imagen_arreglo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadata',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
