# Generated by Django 4.2.11 on 2026-06-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_alter_videometadata_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videometadata',
            name='id_video_equipo',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='imagen_arreglo',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='prompt_imagen_arreglo',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='prompt_video_arreglo',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='video_arreglo',
        ),
        migrations.AlterField(
            model_name='videometadata',
            name='drive_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videometadata',
            name='imagen_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videometadata',
            name='video_original_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
