# Generated by Django 4.2.11 on 2026-06-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_remove_videometadata_id_video_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='id_video_equipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='imagen_arreglo_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='prompt_imagen_arreglo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='prompt_video_arreglo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='video_arreglo_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
