# Generated by Django 4.2.11 on 2026-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_videometadata_id_video_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadata',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videometadata',
            name='id_video_equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videometadata',
            name='mateo_miguel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
