# Generated by Django 4.2.11 on 2026-06-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_alter_videometadata_duracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videometadata',
            name='imagen_arreglo_link',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='prompt_imagen_arreglo',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='prompt_video_arreglo',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='video_arreglo_link',
        ),
    ]
