# Generated by Django 4.2.11 on 2026-06-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_remove_videometadata_imagen_arreglo_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videometadata',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='id_video_equipo',
        ),
        migrations.AlterField(
            model_name='videometadata',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
