# Generated by Django 4.2.11 on 2026-06-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_remove_videometadata_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='id_video_equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
