# Generated by Django 4.2.11 on 2026-06-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0012_videometadata_id_video_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videometadata',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
