# Generated by Django 4.2.11 on 2026-06-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_videometadata_genero_alter_videometadata_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='imagen_arreglo_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='prompt_imagen_arreglo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='prompt_video_arreglo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='video_arreglo_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
