# Generated by Django 4.2.11 on 2026-06-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_videometadata_imagen_arreglo_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadata',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
