# Generated by Django 4.2.11 on 2026-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0015_alter_videometadata_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videometadata',
            name='imagen_arreglo_link',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='prompt_imagen_arreglo',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='prompt_video_arreglo',
        ),
        migrations.RemoveField(
            model_name='videometadata',
            name='video_arreglo_link',
        ),
        migrations.AlterField(
            model_name='videometadata',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
